version: '3.8'

services:
  mountebank:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mountebank
    ports:
      - "2525:2525"
      - "4545:4545"
      - "4546:4546"
    volumes:
      - ./inject:/inject
      - ./imposters.json:/imposters.json