version: '3.8'

services:
  mockserver:
    image: mockserver/mockserver:latest
    container_name: mockserver
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_LOG_LEVEL: INFO
    volumes:
      - ./setup-mockserver.sh:/usr/local/bin/setup-mockserver.sh

  mountebank:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mountebank
    ports:
      - "2525:2525"
      - "4545:4545"
      - "4546:4546"
    volumes:
      - ./imposters.json:/imposters.json